# Generated by Django 4.2.28 on 2026-02-08 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('upload_timestamp', models.DateTimeField(auto_now_add=True)),
                ('total_equipment_count', models.IntegerField(default=0)),
                ('avg_flowrate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('avg_pressure', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('avg_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('file_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datasets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-upload_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PDFReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_filename', models.CharField(max_length=255)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField(default=0)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='api.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentTypeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(db_index=True, max_length=100)),
                ('count', models.IntegerField(default=0)),
                ('avg_flowrate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('avg_pressure', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('avg_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('min_flowrate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_flowrate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('min_pressure', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_pressure', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('min_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_summaries', to='api.dataset')),
            ],
            options={
                'verbose_name_plural': 'Equipment type summaries',
                'ordering': ['equipment_type'],
                'indexes': [models.Index(fields=['dataset_id', 'equipment_type'], name='api_equipme_dataset_786b2b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(max_length=255)),
                ('equipment_type', models.CharField(db_index=True, max_length=100)),
                ('flowrate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pressure', models.DecimalField(decimal_places=2, max_digits=12)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=12)),
                ('row_number', models.IntegerField(default=0)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_list', to='api.dataset')),
            ],
            options={
                'verbose_name_plural': 'Equipment',
                'ordering': ['row_number'],
                'indexes': [models.Index(fields=['dataset_id', 'equipment_type'], name='api_equipme_dataset_5f63bb_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='dataset',
            index=models.Index(fields=['upload_timestamp'], name='api_dataset_upload__b4cc85_idx'),
        ),
    ]
